# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import jfjoch_pb2 as jfjoch__pb2


class gRPC_JFJochBrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Start',
                request_serializer=jfjoch__pb2.BrokerSetup.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Stop',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Abort = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Abort',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Cancel = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Cancel',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Pedestal = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Pedestal',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Initialize = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Initialize',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Deactivate = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Deactivate',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Setup = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/Setup',
                request_serializer=jfjoch__pb2.BrokerPersistentSettings.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.GetSetup = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetSetup',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.BrokerPersistentSettings.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetStatus',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.BrokerStatus.FromString,
                )
        self.GetCalibration = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetCalibration',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.JFCalibration.FromString,
                )
        self.GetFullStatus = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetFullStatus',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.BrokerFullStatus.FromString,
                )
        self.GetDataProcessingSettings = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetDataProcessingSettings',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.DataProcessingSettings.FromString,
                )
        self.SetDataProcessingSettings = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/SetDataProcessingSettings',
                request_serializer=jfjoch__pb2.DataProcessingSettings.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.LoadMask = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/LoadMask',
                request_serializer=jfjoch__pb2.MaskToLoad.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.GetMask = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetMask',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Image.FromString,
                )
        self.GetMaskRawCoord = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetMaskRawCoord',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Image.FromString,
                )
        self.GetPedestalG0 = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG0',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Image.FromString,
                )
        self.GetPedestalG1 = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG1',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Image.FromString,
                )
        self.GetPedestalG2 = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG2',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Image.FromString,
                )
        self.GetPreviewFrame = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochBroker/GetPreviewFrame',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.PreviewFrame.FromString,
                )


class gRPC_JFJochBrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pedestal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deactivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Setup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataProcessingSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDataProcessingSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaskRawCoord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPedestalG0(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPedestalG1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPedestalG2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreviewFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=jfjoch__pb2.BrokerSetup.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Pedestal': grpc.unary_unary_rpc_method_handler(
                    servicer.Pedestal,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Deactivate': grpc.unary_unary_rpc_method_handler(
                    servicer.Deactivate,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Setup': grpc.unary_unary_rpc_method_handler(
                    servicer.Setup,
                    request_deserializer=jfjoch__pb2.BrokerPersistentSettings.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'GetSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetup,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.BrokerPersistentSettings.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.BrokerStatus.SerializeToString,
            ),
            'GetCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalibration,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.JFCalibration.SerializeToString,
            ),
            'GetFullStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullStatus,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.BrokerFullStatus.SerializeToString,
            ),
            'GetDataProcessingSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataProcessingSettings,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.DataProcessingSettings.SerializeToString,
            ),
            'SetDataProcessingSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDataProcessingSettings,
                    request_deserializer=jfjoch__pb2.DataProcessingSettings.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'LoadMask': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMask,
                    request_deserializer=jfjoch__pb2.MaskToLoad.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'GetMask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMask,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Image.SerializeToString,
            ),
            'GetMaskRawCoord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaskRawCoord,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Image.SerializeToString,
            ),
            'GetPedestalG0': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPedestalG0,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Image.SerializeToString,
            ),
            'GetPedestalG1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPedestalG1,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Image.SerializeToString,
            ),
            'GetPedestalG2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPedestalG2,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Image.SerializeToString,
            ),
            'GetPreviewFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreviewFrame,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.PreviewFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochBroker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Start',
            jfjoch__pb2.BrokerSetup.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Stop',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Abort',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Cancel',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pedestal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Pedestal',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Initialize',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deactivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Deactivate',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Setup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/Setup',
            jfjoch__pb2.BrokerPersistentSettings.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetSetup',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.BrokerPersistentSettings.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetStatus',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.BrokerStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetCalibration',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.JFCalibration.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFullStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetFullStatus',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.BrokerFullStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataProcessingSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetDataProcessingSettings',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.DataProcessingSettings.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDataProcessingSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/SetDataProcessingSettings',
            jfjoch__pb2.DataProcessingSettings.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/LoadMask',
            jfjoch__pb2.MaskToLoad.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetMask',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaskRawCoord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetMaskRawCoord',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPedestalG0(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG0',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPedestalG1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG1',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPedestalG2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetPedestalG2',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPreviewFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochBroker/GetPreviewFrame',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.PreviewFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class gRPC_JFJochReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/Start',
                request_serializer=jfjoch__pb2.ReceiverInput.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Abort = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/Abort',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Cancel = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/Cancel',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/Stop',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.ReceiverOutput.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/GetStatus',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.ReceiverStatus.FromString,
                )
        self.SetDataProcessingSettings = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/SetDataProcessingSettings',
                request_serializer=jfjoch__pb2.DataProcessingSettings.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.GetPreviewFrame = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/GetPreviewFrame',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.PreviewFrame.FromString,
                )
        self.GetNetworkConfig = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochReceiver/GetNetworkConfig',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.ReceiverNetworkConfig.FromString,
                )


class gRPC_JFJochReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDataProcessingSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreviewFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=jfjoch__pb2.ReceiverInput.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.ReceiverOutput.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.ReceiverStatus.SerializeToString,
            ),
            'SetDataProcessingSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDataProcessingSettings,
                    request_deserializer=jfjoch__pb2.DataProcessingSettings.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'GetPreviewFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreviewFrame,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.PreviewFrame.SerializeToString,
            ),
            'GetNetworkConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkConfig,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.ReceiverNetworkConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochReceiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochReceiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/Start',
            jfjoch__pb2.ReceiverInput.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/Abort',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/Cancel',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/Stop',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.ReceiverOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/GetStatus',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.ReceiverStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDataProcessingSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/SetDataProcessingSettings',
            jfjoch__pb2.DataProcessingSettings.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPreviewFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/GetPreviewFrame',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.PreviewFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochReceiver/GetNetworkConfig',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.ReceiverNetworkConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class gRPC_JFJochWriterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochWriter/Start',
                request_serializer=jfjoch__pb2.WriterInput.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Abort = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochWriter/Abort',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochWriter/Stop',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.WriterOutput.FromString,
                )
        self.WriteMasterFile = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochWriter/WriteMasterFile',
                request_serializer=jfjoch__pb2.WriterMetadataInput.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )


class gRPC_JFJochWriterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteMasterFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochWriterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=jfjoch__pb2.WriterInput.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.WriterOutput.SerializeToString,
            ),
            'WriteMasterFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMasterFile,
                    request_deserializer=jfjoch__pb2.WriterMetadataInput.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochWriter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochWriter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochWriter/Start',
            jfjoch__pb2.WriterInput.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochWriter/Abort',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochWriter/Stop',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.WriterOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteMasterFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochWriter/WriteMasterFile',
            jfjoch__pb2.WriterMetadataInput.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class gRPC_JFJochDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/Start',
                request_serializer=jfjoch__pb2.DetectorInput.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/Stop',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Status = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/Status',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.DetectorStatus.FromString,
                )
        self.On = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/On',
                request_serializer=jfjoch__pb2.DetectorConfig.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Off = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/Off',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Trigger = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochDetector/Trigger',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )


class gRPC_JFJochDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def On(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Off(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=jfjoch__pb2.DetectorInput.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.DetectorStatus.SerializeToString,
            ),
            'On': grpc.unary_unary_rpc_method_handler(
                    servicer.On,
                    request_deserializer=jfjoch__pb2.DetectorConfig.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Off': grpc.unary_unary_rpc_method_handler(
                    servicer.Off,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Trigger,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/Start',
            jfjoch__pb2.DetectorInput.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/Stop',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/Status',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.DetectorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def On(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/On',
            jfjoch__pb2.DetectorConfig.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Off(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/Off',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochDetector/Trigger',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class gRPC_JFJochTriggerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trigger = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochTrigger/Trigger',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )


class gRPC_JFJochTriggerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochTriggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Trigger,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochTrigger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochTrigger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochTrigger/Trigger',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class gRPC_JFJochIndexerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochIndexer/Start',
                request_serializer=jfjoch__pb2.IndexerInput.SerializeToString,
                response_deserializer=jfjoch__pb2.Empty.FromString,
                )
        self.Stop = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochIndexer/Stop',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.IndexerOutput.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/JFJochProtoBuf.gRPC_JFJochIndexer/GetStatus',
                request_serializer=jfjoch__pb2.Empty.SerializeToString,
                response_deserializer=jfjoch__pb2.IndexerStatus.FromString,
                )


class gRPC_JFJochIndexerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPC_JFJochIndexerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=jfjoch__pb2.IndexerInput.FromString,
                    response_serializer=jfjoch__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.IndexerOutput.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jfjoch__pb2.Empty.FromString,
                    response_serializer=jfjoch__pb2.IndexerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JFJochProtoBuf.gRPC_JFJochIndexer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC_JFJochIndexer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochIndexer/Start',
            jfjoch__pb2.IndexerInput.SerializeToString,
            jfjoch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochIndexer/Stop',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.IndexerOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JFJochProtoBuf.gRPC_JFJochIndexer/GetStatus',
            jfjoch__pb2.Empty.SerializeToString,
            jfjoch__pb2.IndexerStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
